= Invalid execution results =
Parallel part:
| operation(): 2 | operation(): 1 |

= The following interleaving leads to the error =
Parallel part trace:
|                      | operation()                                                                                                         |
|                      |   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:90) |
|                      |   counter.READ: 0 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                        |
|                      |   counter.WRITE(1) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                       |
|                      |   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                        |
|                      |   switch                                                                                                            |
| operation(): 2       |                                                                                                                     |
|   thread is finished |                                                                                                                     |
|                      |   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                       |
|                      |   result: 1                                                                                                         |
|                      |   thread is finished                                                                                                |

Detailed parallel part trace:
|                                                                                                                     | operation()                                                                                                         |
|                                                                                                                     |   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:90) |
|                                                                                                                     |     useless.READ: 0 at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:98)                      |
|                                                                                                                     |     useless.WRITE(1) at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:98)                     |
|                                                                                                                     |   counter.READ: 0 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                        |
|                                                                                                                     |   counter.WRITE(1) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                       |
|                                                                                                                     |   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                        |
|                                                                                                                     |   switch                                                                                                            |
| operation()                                                                                                         |                                                                                                                     |
|   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:90) |                                                                                                                     |
|     useless.READ: 1 at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:98)                      |                                                                                                                     |
|     useless.WRITE(2) at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:98)                     |                                                                                                                     |
|   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                        |                                                                                                                     |
|   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:92)                       |                                                                                                                     |
|   counter.READ: 2 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                        |                                                                                                                     |
|   counter.WRITE(3) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                       |                                                                                                                     |
|   result: 2                                                                                                         |                                                                                                                     |
|   thread is finished                                                                                                |                                                                                                                     |
|                                                                                                                     |   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:93)                       |
|                                                                                                                     |   result: 1                                                                                                         |
|                                                                                                                     |   thread is finished                                                                                                |